name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: WPCS validate
      run: vendor/bin/phpcs -p -s --colors --standard=phpcs.xml .

    - name: PHPUnit tests
      run: vendor/bin/phpunit -c tests/phpunit/phpunit.xml

    - name: Tests coverage
      run: vendor/phpunit/phpunit/phpunit --configuration tests/phpunit/phpunit.xml --coverage-clover coverage.xml \
          php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v
